### ISSUE TITLE
Field clarifications

### ISSUE THREAD

**Issue by ndarilek** [jagi/meteor-astronomy-docs#14]
I'm interested in transitioning from collection2/document-methods/collection-helpers to this package, but I'm not clear on some things. Maybe I missed them in the docs, but figured I'd file them as an issue against this repo so the answers might be included.

If I specify a list of fields on a class, what happens when I:
- Add a document to the collection via class instantiation that includes fields not in the list?
- Add a document to the collection via direct collection access that includes fields not in the list?
- Add a document via direct collection access that otherwise violates the schema?

IOW, I'm not clear on whether the field list is treated as definitive. collection2 I think has an option that lets it not complain if docs have extra fields so I could see this going either way.

I'm also not clear if it effects documents not created as classes. One aspect I like about collection2 is that it blocks _any_ attempt to create a non-conforming doc. Ideally everyone working on my codebase will use the Astronomy classes, but it'd be great if Astronomy also caught errors caused by someone directly inserting into the underlying collection.

Thanks.

**Comment by lukejagodzinski** [comment]
1. It will print a warning in the console that you cannot do it. Extra fields won't be added to the document. It's why a schema exists. We don't want any extra fields. If you need an extra field and you don't want to specify its type you can use `null` instead specifying a type.
2. A field will be added and it will be published to the client if you do so. However, when fetching, a given field will be omitted and won't be present in a document.
3. Isn't it the same as previous?

If you want to use Astronomy, you probably care about data integrity and that's why Astronomy does not allow extra fields. It may sound bad, but if you consider that Astronomy will work with other databases in the future then it may sound better. MongoDB doesn't prevent you from adding any extra fields, but SQL does. Astronomy is ORM/ODM and it has to follow these rules. Collection2/document-methods/collection-helpers are not ORM/ODM so you can do whatever you want with your model.

Having flexibility is sometimes good but you can mess you database structure. In reality, almost in every project I've seen, developers tried to create some constraints on data to keep model's integrity even if they were playing with databases like MongoDB.

**Comment by ndarilek** [comment]
"It may sound bad,"

Actually, it doesn't. That's exactly what I was hoping to hear. :)

As per points 2 and 3 above, I wanted to make sure that someone couldn't 
pollute my models with extra fields. That's a bit different than a 
constraint violation on an existing field.

Thanks, I wasn't sure how eagerly Astronomy enforced its constraints, 
and what might happen if something went around them (I.e. another Meteor 
package like an admin interface accessed my collections directly.) 
Sounds like I'll be replacing half a dozen or so packages.

**Comment by lukejagodzinski** [comment]
Closing this issue for now :)
